### ISSUE TITLE
Steps only works with total steps 10

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-steps-v2-changelog#1]
Hy,

please check this bug:

![Screenshot (65)](https://user-images.githubusercontent.com/5861215/145673035-c2db6b7a-28a0-4f66-ab06-d3fbf2606ad5.png)

I set the total step to 6 and current step to 6...

this is the markup:

```
<div class="container max-width-md margin-top-xxl">    
    <div class="steps-v2 " style="--step-v2-current-step: 6;">
        <p class="text-sm color-contrast-medium margin-bottom-xs">
            Step <span class="js-steps-v2__current-step">6</span> of <span class="js-steps-v2__tot-steps">6</span>
        </p>

        <div class="steps-v2__indicator" aria-hidden="true"></div>
    </div>
</div>
```

Thank you

**Comment by claudia-romano** [comment]
Hi Dario, you will need to update the --steps-v2-steps-nr variable as well. We have updated the component info page to include a reference to that variable as well:
https://codyhouse.co/ds/components/info/steps-v2

Cheers!
